<?php
/**
 * @file
 * Tell Drupal about the custom template.
 */

/**
 * Implements hook_theme().
 */
function stanford_block_type_hero_theme() {
  $theme['block__bundle__hero_block'] = [
    'template' => 'block--bundle--hero_block',
  ];
  return $theme;
}

/**
 * Implements hook_theme_registry_alter
 */
function stanford_block_type_hero_theme_registry_alter(&$theme_registry) {
  $theme_registry['block__bundle__hero_block']['path'] = drupal_get_path('module', 'stanford_block_type_hero') . '/templates';
}
